### Lynda.com
NumPy Data Science Essential Training: Create arrays from Python structures

In [1]:
import numpy as np # import numpy library as np

In [3]:
print(np.__version__) #check numpy version

1.11.1


In [4]:
my_list = [-17, 0, 4, 5, 9] # python's list
my_array_from_list = np.array(my_list) # put this python list into numpy array
my_array_from_list

array([-17,   0,   4,   5,   9])

In [5]:
my_array_from_list * 10 # multiply all elements in the array by 10

array([-170,    0,   40,   50,   90])

In [6]:
my_tuple = (14, -3.54, 5+7j) # create a python tuple
np.array(my_tuple) # note that each element in the tuple was "promoted" to complex numbers. 
# ie. 14 becomes a floating number plus complex/imaginary part

array([ 14.00+0.j,  -3.54+0.j,   5.00+7.j])

### Note the difference between numpy and python data structure!

In [7]:
my_tuple * 6 # python tuple is replicated six times

(14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j))

In [8]:
np.array(my_tuple) * 6 # each element in the tuple is multiplied by six

array([ 84.00 +0.j, -21.24 +0.j,  30.00+42.j])

The operator and its impact will vary, depending upon the type of data structure that you're using. This difference is an example of object-oriented design, within both numpy and python.