## Lynda.com
Numpy broadcasting

In [1]:
import numpy as np

In [3]:
my_3D_array = np.arange(70) # create a 1D array with elements from 0 to 69.
my_3D_array.shape = (2, 7, 5) 
# reshape it into two 2D arrays with 7 rows and 5 columns each
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

Broadcasting describes how numpy performs operations between arrays with differnt sizes.
Numpy requires that arrays be compatible before broadcasting can take place. In this context, compatible means that the sizes are the same or at least one of the sizes is equal to zero.
Thus, we need to know the attributes of the arrays before we can do broadcasting correctly.

Attributes of numpy arrays
- shapes
- number of dimensions
- sizes
- data types

In [4]:
# first, let's check the shape
my_3D_array.shape # exactly the same as we specified. no surprise

(2, 7, 5)

In [5]:
# check the number of dimensions
# when we are coding programmatically instead of interactively, 
# we have to be able to access this information programmatically
my_3D_array.ndim

3

In [6]:
# check the size (number of elements) in the array
my_3D_array.size

70

In [7]:
# check the data type for each element
my_3D_array.dtype
# note that the dtype for the elements is 32-bit integer but the dtype for the array is ndarray

dtype('int32')

In [8]:
# broadcasting using scaler
5 * my_3D_array -2 # multiply each element by 5 then subtract by 2
# this operation is compatible because numpy treats scalars as having a size equal to one

array([[[ -2,   3,   8,  13,  18],
        [ 23,  28,  33,  38,  43],
        [ 48,  53,  58,  63,  68],
        [ 73,  78,  83,  88,  93],
        [ 98, 103, 108, 113, 118],
        [123, 128, 133, 138, 143],
        [148, 153, 158, 163, 168]],

       [[173, 178, 183, 188, 193],
        [198, 203, 208, 213, 218],
        [223, 228, 233, 238, 243],
        [248, 253, 258, 263, 268],
        [273, 278, 283, 288, 293],
        [298, 303, 308, 313, 318],
        [323, 328, 333, 338, 343]]])

In [10]:
# creating two numpy arrays
left_matrix = np.arange(6).reshape((2,3)) 
# a 2D array of 2 rows and 3 columns with elements 0 to 5
right_matrix = np.arange(15).reshape((3,5))
# a 2D array of 3 rows and 5 columns with elements from 0 to 15.

# note: even though these variables are named as matrices, 
# they are actually just ordinary ndarrays.
# matrices are a specific type within numpy

In [11]:
np.inner(left_matrix, right_matrix)
# inner product of left_matrix and right_matrix yields an error
# in linear algebra, if you multiply a 2-by-3 matrix and a 3-by-5 matrix, you will obtain
# a result that is a 2-by-5 matrix. However, if we use Numpy's function, it tells us that
# the shapes are not aligned.

# from Numpy inner product function documentation,  
# it tells us that we obtain the ordinary inner product
# of vectors for one-dimensional arrays. In higher dimensions, a sum product over the last axes.

ValueError: shapes (2,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [13]:
# we should use the numpy dot product function.
# numpy dot product function gives us the anticipated result.
np.dot(left_matrix, right_matrix)
# the numpy dot product documentation says that
# for 2D arrays, it is equivalent to matrix multiplication
# for 1D arrays it is equivalent to the inner product of vectors
# For ND arrays, it is a sum product over the last axis of a and the second-to-last of b

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

*** Take-home lesson: check numpy documentations carefully before you perform complex operations ***

### Operations along axes

In [15]:
my_3D_array.sum() # sum up all the elements in the array

2415

In [17]:
# use Gauss' formula to calculate the sum of 70 elements from 0 to 69
(69 * 70)/2
# note that the output is a floating number

2415.0

In [18]:
my_3D_array.sum(axis=0)
# sum along the zero axis
# for example 35 = 0 + 35
# 37 = 1 + 36
# 39 = 2 + 37
# elementwise addtion of the two 2D arrays 

array([[ 35,  37,  39,  41,  43],
       [ 45,  47,  49,  51,  53],
       [ 55,  57,  59,  61,  63],
       [ 65,  67,  69,  71,  73],
       [ 75,  77,  79,  81,  83],
       [ 85,  87,  89,  91,  93],
       [ 95,  97,  99, 101, 103]])

In [19]:
my_3D_array.sum(axis=1)
# for example, the 105 is a sum along the axis 30+25+20+15+10+5+0=105

array([[105, 112, 119, 126, 133],
       [350, 357, 364, 371, 378]])

In [20]:
my_3D_array.sum(axis=2)
# for example the 10 is a sum along the axis 0+1+2+3+4=10

array([[ 10,  35,  60,  85, 110, 135, 160],
       [185, 210, 235, 260, 285, 310, 335]])

Notice how the shape attribute affects broadcasting along an axis. 
- If we broadcast along the zero axis, we eliminate the zero element in the shape attribute. The result is 7 rows by 5 columns. (2,7,5) -> (7,5)
- If we broadcast along the one axis, we eliminate the one element and the result is 2 rows by 5 columns. (2,7,5)->(2,5) 
- If we broadcast along the two axis, we eliminate the zeroth element and the result is 2 rows by 7 columns. (2,7,5)->(2,7)

### Broadcasting rules
Numpy documentation tells us that the smaller array is broadcast across the larger array so that they have compatible shapes.

In [21]:
my_2D_array = np.ones(35, dtype='int_').reshape((7,5))*3
# create a 1D array of 35 ones and reshape it into 2D as 7 rows and 5 columns
# then multiply all elements by 3
my_2D_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [22]:
my_random_2D_array = np.random.random((7,5))
# create a 1D array of 35 random numbers and reshape it into 2D as 7 rows and 5 columns

In [23]:
np.set_printoptions(precision=4) # use set_printoptions function to specify the floating point
# to 4 decimal places
my_3D_array * my_random_2D_array
# the broadcasting rule is satisfied so no error message

array([[[  0.    ,   0.805 ,   1.8353,   0.4801,   3.899 ],
        [  4.9297,   3.9097,   4.9651,   1.4783,   2.5223],
        [  5.7924,   0.9991,   9.2228,   2.5809,   8.6615],
        [  7.2541,   5.8767,   7.1   ,  13.3775,  16.8187],
        [ 15.3088,   8.1106,   0.4207,   3.387 ,  13.2661],
        [ 21.19  ,  13.8113,  17.313 ,  22.7997,   0.1136],
        [  8.5604,  26.0245,  14.6895,  12.6039,  12.7265]],

       [[ 12.8816,  28.9784,  33.9526,   6.0816,  38.0149],
        [ 39.4378,  26.7162,  29.7905,   7.9459,  12.3311],
        [ 26.0658,   4.1781,  36.1225,   9.5294,  30.3152],
        [ 24.1802,  18.7319,  21.7177,  39.3892,  47.8005],
        [ 42.0993,  21.6282,   1.0899,   8.5411,  32.6125],
        [ 50.8561,  32.4035,  39.7558,  51.2993,   0.2506],
        [ 18.5475,  55.407 ,  30.7562,  25.9716,  25.8273]]])

In [24]:
bad_2D_array = np.ones(64, dtype='int_').reshape((8,8))*2
# create a 1D array of 64 ones and reshape it into 2D as 8 rows and 8 columns
# then multiply all elements by 2
bad_2D_array

array([[2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2]])

In [25]:
bad_2D_array * my_3D_array
# incompatible shapes ...

ValueError: operands could not be broadcast together with shapes (8,8) (2,7,5) 

In [26]:
bad_2D_array_1 = np.ones(14, dtype='int_').reshape((2,7))*2
bad_2D_array_1

array([[2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])

In [27]:
bad_2D_array_1 * my_3D_array
# incompatible shapes ...

ValueError: operands could not be broadcast together with shapes (2,7) (2,7,5) 