### Lynda.com
NumPy Data Science Essential Training: 
Intrinsic Numpy array creation using NumPy's methods

In [1]:
import numpy as np

In [2]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [3]:
np.arange(10, 23) # create a range from 10 to 22

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [7]:
# check that we actually have 13 elements in the array
np.arange(10, 23)-10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
# another way to check the number of elements
len(np.arange(10, 23))

13

In [9]:
# another way to check the number of elements using numpy built-in function
my_range_array = np.arange(10, 23)
my_range_array.size

13

In [10]:
# another way to check 
np.arange(10, 23).size

13

In [11]:
np.arange(10, 23, 5) # 10 is the start parameter. 23 is the stop parameter. 
# 5 is the step parameter.
# remember that numpy includes the start parameter and excludes the stop parameter

array([10, 15, 20])

In [12]:
# in comparison
np.arange(10, 26, 5)
# this array has four elements

array([10, 15, 20, 25])

In [14]:
np.arange(26, step=5)
# this example workds without the start parameter being specified.
# it is inconsistent with the documentation of numpy saying that a start parameter must be 
# specified when a step parameter
# one possibility: the volunteer that wrote the documentation and the volunteer who implemented
# the function are two different people
# best practice: even though this example still works, we should revise our example to make it
# consistent with the documentation

array([ 0,  5, 10, 15, 20, 25])

In [15]:
np.arange(0, 26, step=5) # in accordance of the documentation

array([ 0,  5, 10, 15, 20, 25])