### Lynda.com
NumPy Data Science Essential Training: linspace(), zeros(), ones(), and Numpy data types

In [2]:
import numpy as np

In [3]:
np.linspace(5, 15, 9) # create an evenly spaced array of 9 elements from 5 to 15 inclusively 

array([  5.  ,   6.25,   7.5 ,   8.75,  10.  ,  11.25,  12.5 ,  13.75,  15.  ])

In [4]:
my_linspace = np.linspace(5, 15, 9, retstep=True) 
# create an evenly spaced array of 9 elements from 5 to 15 inclusively 
# show the step size

In [5]:
my_linspace # note that the step size 1.25 is shown as a second component

(array([  5.  ,   6.25,   7.5 ,   8.75,  10.  ,  11.25,  12.5 ,  13.75,  15.  ]),
 1.25)

In [6]:
my_linspace[1] # to access its second component

1.25

### zeros()

In [7]:
np.zeros(5) # creates a one-dimensional array of 5 elements, all zeros

array([ 0.,  0.,  0.,  0.,  0.])

### ones()

In [9]:
np.ones(7) # creates a one-dimensional array of 7 elements, all ones
# similar to the zeros function

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.])

### Creating multi-dimensional arrays
- by passing a tuple of shapes to either ones or zeros

In [14]:
np.zeros((5,4)) # create an 2D array with 5 rows and 4 columns
# note that the output begins and ends with double square brackets
# having two square brackets means 2 dimensions

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [20]:
# now we try a 3D array
np.zeros((5, 4, 3))
# first component 5 means "you get five 2D arrays"
# second component 4 means "you get 4 groups of matrices" or "4 rows"
# third component 3 means "you get 3 columns"
# 5 by 4 by 3

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [25]:
np.zeros((2, 4, 3))
# You get a 3D array that has two 2D arrays, 4 groups of matrices or 4 rows, 3 columns
# 2 by 4 by 3

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

### Specify the data type of an array

In [18]:
np.zeros(11, dtype='int64') # create a 1D array with 11 zeros that are 64-bit integer.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [19]:
np.zeros(11) # if dtype is not specified, the defaut of zeros() and ones()
# give you floating point values

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])