## Lynda.com
numpy essential training: finding patterns 

In [1]:
import numpy as np

### Given this array, find the next number in the sequence

In [2]:
my_teaser_array = np.array([1, 7, 19, 37, 61, 91, 127, 169, 217, 271, 331])
my_teaser_array

array([  1,   7,  19,  37,  61,  91, 127, 169, 217, 271, 331])

For information about numpy.diff, please see http://docs.scipy.org/doc/numpy/reference/generated/numpy.diff.html

Difference equations are mathematical constructs that provide methods for analyzing differences in data elements.

In [3]:
np.diff(my_teaser_array) # get the first difference

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54, 60])

Every element is divisible by six. You lose an element with each layer of difference.

In [4]:
np.diff(my_teaser_array, n=2) # get the second difference

array([6, 6, 6, 6, 6, 6, 6, 6, 6])

In [5]:
np.diff(my_teaser_array, n=3) # get the third element

array([0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
from sympy import init_session
init_session()

IPython console for SymPy 1.0 (Python 3.5.2-64-bit) (ground types: python)

These commands were executed:
>>> from __future__ import division
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)
>>> init_printing()

Documentation can be found at http://docs.sympy.org/1.0/


Let's use SymPy's diff function to calculcate the derivative of x exponentiated to the third power

In [7]:
diff(x**3)

In [8]:
# calculate the second derivative with respect to x
diff(x**3, x, 2)

In [9]:
diff(x**3, x, 3) # third derivative

In [10]:
diff(x**3, x, 4) # fourth derivative

In [11]:
def my_guess(n):
    return (n+1)**3 - n**3

In [12]:
my_guess(np.arange(20))

array([   1,    7,   19,   37,   61,   91,  127,  169,  217,  271,  331,
        397,  469,  547,  631,  721,  817,  919, 1027, 1141], dtype=int32)