## Lynda.com
numpy essential training: mainuplate arrays - rearranging array elements

In [1]:
import numpy as np
my_start_array = np.array(np.arange(24))
my_3_8_array = my_start_array.reshape((3,8))
my_2_3_4_array = my_3_8_array.reshape((2,3,4))

### fliplr "flip left right"
from: http://docs.scipy.org/dc/numpy/reference/generated/numpy.fliplr.html#numpy.fliplr

Flip array in the left/right direction.

In [7]:
# examine my_3_8_array and my_2_3_4_array
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [8]:
my_2_3_4_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [3]:
np.fliplr(my_3_8_array)

array([[ 7,  6,  5,  4,  3,  2,  1,  0],
       [15, 14, 13, 12, 11, 10,  9,  8],
       [23, 22, 21, 20, 19, 18, 17, 16]])

In [4]:
np.fliplr(my_2_3_4_array)

array([[[ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[20, 21, 22, 23],
        [16, 17, 18, 19],
        [12, 13, 14, 15]]])

The function says left to right but the displayed presentation is bottom to top. This is consistent with the definition where *flipping takes place over the last index!*

### flipup "flip up down"

In [9]:
np.flipud(my_3_8_array)

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5,  6,  7]])

In [10]:
np.flipud(my_2_3_4_array)

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

Here, the result is applied to a 3D aray and what's occurred in the previously first 2D matrix is now in the 