## Lynda.com
numpy essential training: manipulate arrays - shape manipulation

In [1]:
import numpy as np

### reshape
from: http://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html#numpy.reshape

note: from the documentation above, especially at the return section, it says "this will be a new view object if possible; otherwise, it will be a copy. Note there is no gaurantee of the memory layout"

In [2]:
my_start_array = np.array(np.arange(24))
my_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [3]:
my_start_array.shape
# it's a 1D array with 24 elements

(24,)

In [4]:
my_3_8_array = my_start_array.reshape((3,8))
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [5]:
# next, let's check and see if my_3_8_array is a view or a copy of my_start_array
my_3_8_array[0,0] = 1234

In [6]:
my_start_array

array([1234,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23])

The element at [0,0] in my_start_array is now 1234!
The reshape function created a view of the data not a copy.

### Ravel
Numpy's ravel function returns a continuous, flattened array.


The documentation tells us that if we apply ravel to a matrix, the return value is a 1D ndarray.

Otherwise, the return value is an array of the same subtypes as the array to which ravel is applied.

In [8]:
my_ravel_array = my_3_8_array.ravel()
my_ravel_array

array([1234,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23])

The single bracket of my_ravel_array indicates a 1D array!

In [9]:
my_ravel_array.shape

(24,)

### Flat
In contrast with ravel, flat does not return an array. Flat returns an iterator. 

In [11]:
for n in my_3_8_array.flat:
    print(n)

1234
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


Since array.flat is an iterator, it can be used in a control statement!