## Lynda.com
numpy essential training: manipulate arrays - joining and splitting

### Joining and splitting arrays
- concatenante
- stack
- split

In [14]:
import numpy as np

### Concatenate

In [15]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
a

array([[1, 2],
       [3, 4]])

In [16]:
b

array([[5, 6]])

In [17]:
together = np.concatenate((a, b), axis=0)
# first parameter: a tuple which contains the arrays to be concatenated
# second parameter: specifies the axis for concatenation

In [18]:
together

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
together.shape

(3, 2)

In [20]:
# let's assign a new value in the array "together"
together[1,1]= 555

In [21]:
# display together again
together

array([[  1,   2],
       [  3, 555],
       [  5,   6]])

In [22]:
# check and see if "together" is a view or copy of the original array 'a'
a
# a is not affected
# thus, 'together' is a copy of the original arrays 'a' and 'c'

array([[1, 2],
       [3, 4]])

In [23]:
# let's evaluate the impact on the function 'concatenate''s axis parameter
c = np.array([[1, 2], [3, 4]]) *3 + 5
c

array([[ 8, 11],
       [14, 17]])

In [24]:
np.concatenate((a, c), axis=1)

array([[ 1,  2,  8, 11],
       [ 3,  4, 14, 17]])

In [25]:
np.concatenate((a, c), axis=2)
# they are 2D arrays so no axis=2

IndexError: axis 2 out of bounds [0, 2)

### Stack

In [32]:
# we will create a list of five arrays, each with 3 rows and 4 columns
arrays = np.zeros((5,3,4))
for n in range(5):
    arrays[n] = np.random.randint(0, 14)
    # each element is populated with random integers from 1 to 10
arrays

array([[[ 12.,  12.,  12.,  12.],
        [ 12.,  12.,  12.,  12.],
        [ 12.,  12.,  12.,  12.]],

       [[  5.,   5.,   5.,   5.],
        [  5.,   5.,   5.,   5.],
        [  5.,   5.,   5.,   5.]],

       [[ 10.,  10.,  10.,  10.],
        [ 10.,  10.,  10.,  10.],
        [ 10.,  10.,  10.,  10.]],

       [[ 13.,  13.,  13.,  13.],
        [ 13.,  13.,  13.,  13.],
        [ 13.,  13.,  13.,  13.]],

       [[  1.,   1.,   1.,   1.],
        [  1.,   1.,   1.,   1.],
        [  1.,   1.,   1.,   1.]]])

In [33]:
stack0 = np.stack(arrays, axis=0)
stack1 = np.stack(arrays, axis=1)
stack2 = np.stack(arrays, axis=2)

In [34]:
# let's examine each of these stack variables
stack0

array([[[ 12.,  12.,  12.,  12.],
        [ 12.,  12.,  12.,  12.],
        [ 12.,  12.,  12.,  12.]],

       [[  5.,   5.,   5.,   5.],
        [  5.,   5.,   5.,   5.],
        [  5.,   5.,   5.,   5.]],

       [[ 10.,  10.,  10.,  10.],
        [ 10.,  10.,  10.,  10.],
        [ 10.,  10.,  10.,  10.]],

       [[ 13.,  13.,  13.,  13.],
        [ 13.,  13.,  13.,  13.],
        [ 13.,  13.,  13.,  13.]],

       [[  1.,   1.,   1.,   1.],
        [  1.,   1.,   1.,   1.],
        [  1.,   1.,   1.,   1.]]])

In [35]:
stack0.shape

(5, 3, 4)

Stack0 contains all elements in the original array

In [36]:
stack1

array([[[ 12.,  12.,  12.,  12.],
        [  5.,   5.,   5.,   5.],
        [ 10.,  10.,  10.,  10.],
        [ 13.,  13.,  13.,  13.],
        [  1.,   1.,   1.,   1.]],

       [[ 12.,  12.,  12.,  12.],
        [  5.,   5.,   5.,   5.],
        [ 10.,  10.,  10.,  10.],
        [ 13.,  13.,  13.,  13.],
        [  1.,   1.,   1.,   1.]],

       [[ 12.,  12.,  12.,  12.],
        [  5.,   5.,   5.,   5.],
        [ 10.,  10.,  10.,  10.],
        [ 13.,  13.,  13.,  13.],
        [  1.,   1.,   1.,   1.]]])

In [37]:
stack1.shape

(3, 5, 4)

stack1 contains three 2D arrays, each with 5 rows and 4 columns

In [38]:
stack2

array([[[ 12.,   5.,  10.,  13.,   1.],
        [ 12.,   5.,  10.,  13.,   1.],
        [ 12.,   5.,  10.,  13.,   1.],
        [ 12.,   5.,  10.,  13.,   1.]],

       [[ 12.,   5.,  10.,  13.,   1.],
        [ 12.,   5.,  10.,  13.,   1.],
        [ 12.,   5.,  10.,  13.,   1.],
        [ 12.,   5.,  10.,  13.,   1.]],

       [[ 12.,   5.,  10.,  13.,   1.],
        [ 12.,   5.,  10.,  13.,   1.],
        [ 12.,   5.,  10.,  13.,   1.],
        [ 12.,   5.,  10.,  13.,   1.]]])

In [39]:
stack2.shape

(3, 4, 5)

stack2 contains three 2D arrays, each with 4 rows and 5 columns

### Split
NumPy Split function separates arrays into two or more sub-arrays

In [40]:
# examine a boundary case
# if the parameter in the split function is less than one, the function returns an error
# if the parameter is equal to one, in this case, we are using the split function
# with our temp array, the parameter is equal to one
# it returns the original array
temp = np.arange(5)
np.split(temp, 1)

[array([0, 1, 2, 3, 4])]

In [41]:
before_split = stack0
before_split.shape

(5, 3, 4)

In [42]:
s0 = np.split(before_split, 5, axis=0)
# split the array into five new arrays along the axis=0
s0

[array([[[ 12.,  12.,  12.,  12.],
         [ 12.,  12.,  12.,  12.],
         [ 12.,  12.,  12.,  12.]]]), array([[[ 5.,  5.,  5.,  5.],
         [ 5.,  5.,  5.,  5.],
         [ 5.,  5.,  5.,  5.]]]), array([[[ 10.,  10.,  10.,  10.],
         [ 10.,  10.,  10.,  10.],
         [ 10.,  10.,  10.,  10.]]]), array([[[ 13.,  13.,  13.,  13.],
         [ 13.,  13.,  13.,  13.],
         [ 13.,  13.,  13.,  13.]]]), array([[[ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.]]])]

In [43]:
type(s0)

list

In [44]:
# each component within s0 is a 2D array with 3 rows and 4 columns
s0[1]

array([[[ 5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.]]])

In [45]:
s0[1].shape
# one 2D array which has 3 rows and 4 columns

(1, 3, 4)

In [46]:
# try split along axis=1
s1 = np.split(before_split, 3, axis=1)
s1

[array([[[ 12.,  12.,  12.,  12.]],
 
        [[  5.,   5.,   5.,   5.]],
 
        [[ 10.,  10.,  10.,  10.]],
 
        [[ 13.,  13.,  13.,  13.]],
 
        [[  1.,   1.,   1.,   1.]]]), array([[[ 12.,  12.,  12.,  12.]],
 
        [[  5.,   5.,   5.,   5.]],
 
        [[ 10.,  10.,  10.,  10.]],
 
        [[ 13.,  13.,  13.,  13.]],
 
        [[  1.,   1.,   1.,   1.]]]), array([[[ 12.,  12.,  12.,  12.]],
 
        [[  5.,   5.,   5.,   5.]],
 
        [[ 10.,  10.,  10.,  10.]],
 
        [[ 13.,  13.,  13.,  13.]],
 
        [[  1.,   1.,   1.,   1.]]])]

In [47]:
# try split along axis=2
s2 = np.split(before_split, 4, axis=2)
s2
# you get a list of 4 new arrays

[array([[[ 12.],
         [ 12.],
         [ 12.]],
 
        [[  5.],
         [  5.],
         [  5.]],
 
        [[ 10.],
         [ 10.],
         [ 10.]],
 
        [[ 13.],
         [ 13.],
         [ 13.]],
 
        [[  1.],
         [  1.],
         [  1.]]]), array([[[ 12.],
         [ 12.],
         [ 12.]],
 
        [[  5.],
         [  5.],
         [  5.]],
 
        [[ 10.],
         [ 10.],
         [ 10.]],
 
        [[ 13.],
         [ 13.],
         [ 13.]],
 
        [[  1.],
         [  1.],
         [  1.]]]), array([[[ 12.],
         [ 12.],
         [ 12.]],
 
        [[  5.],
         [  5.],
         [  5.]],
 
        [[ 10.],
         [ 10.],
         [ 10.]],
 
        [[ 13.],
         [ 13.],
         [ 13.]],
 
        [[  1.],
         [  1.],
         [  1.]]]), array([[[ 12.],
         [ 12.],
         [ 12.]],
 
        [[  5.],
         [  5.],
         [  5.]],
 
        [[ 10.],
         [ 10.],
         [ 10.]],
 
        [[ 13.],
         [ 13.

In [48]:
s2[1].shape

(5, 3, 1)