## Lynda.com
numpy essential training: manipulate arrays- adding and removing elements from NumPy arrays

- append
- horizontal stacking
- vertical stacking
- insert
- delete

In [15]:
import numpy as np

### append

In [3]:
a = np.array(np.arange(24)).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [4]:
b = np.append(a, [5, 6, 7, 8])
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  5,  6,  7,  8])

In [5]:
b.shape

(28,)

In [6]:
b.reshape((7,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 5,  6,  7,  8]])

In [7]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

Note that the variable a is not affected in its row, column or shape

In [8]:
c = a = np.array(np.arange(24)).reshape(2,3,4) * 10 + 3
c

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [9]:
np.append(a, c, axis=0) # append a and c along axis 0

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]],

       [[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [10]:
# now check the shape (without counting the parentheses)
np.append(a, c, axis=0).shape

(4, 3, 4)

In [11]:
np.append(a, c, axis=1) # append a and c along axis 1

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [12]:
np.append(a, c, axis=1).shape # examine its shape in the same fashion

(2, 6, 4)

In [13]:
np.append(a, c, axis=2) # append a and c along axis 2

array([[[  3,  13,  23,  33,   3,  13,  23,  33],
        [ 43,  53,  63,  73,  43,  53,  63,  73],
        [ 83,  93, 103, 113,  83,  93, 103, 113]],

       [[123, 133, 143, 153, 123, 133, 143, 153],
        [163, 173, 183, 193, 163, 173, 183, 193],
        [203, 213, 223, 233, 203, 213, 223, 233]]])

In [14]:
np.append(a, c, axis=2).shape

(2, 3, 8)

### horizontal stacking

In [16]:
my_hay_stack = np.hstack((a,c))
# hstack is a convenience function that eliminates the need of axis parameter
# it returns the same the result as append and/or concatenate
my_hay_stack

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [17]:
my_hay_stack[0,0,2] = 999

In [18]:
my_hay_stack
# 999 is now in the array

array([[[  3,  13, 999,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [19]:
a
# 999 is not added to the array

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [20]:
c
# 999 is also not present 

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

### Insert
Remember to read the documentation for insert function
Pay special attention to the obj parameter
Obj parameter can be regarded as a where parameter.
It indicates where the information in the values parameter will be inserted within the array.
It is similar to using index slices in array selection, and/or array assignments. Another reason to read this documentation is b/c the result is not intuitive. 

In [21]:
after_insert_array = np.insert(c, 1, 444, axis=0)
after_insert_array

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[444, 444, 444, 444],
        [444, 444, 444, 444],
        [444, 444, 444, 444]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

We have inserted an entire new 2D array between the previously first 2D array and the previously last 2D array. 

In [22]:
after_insert_array = np.insert(c, 1, 444, axis=1) # try on axis 1
after_insert_array

array([[[  3,  13,  23,  33],
        [444, 444, 444, 444],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [444, 444, 444, 444],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

The result: each row with an index equal to one now contains elements where the value of each element is 444.

In [24]:
after_insert_array = np.insert(c, 1, 444, axis=2)
after_insert_array

array([[[  3, 444,  13,  23,  33],
        [ 43, 444,  53,  63,  73],
        [ 83, 444,  93, 103, 113]],

       [[123, 444, 133, 143, 153],
        [163, 444, 173, 183, 193],
        [203, 444, 213, 223, 233]]])

The second column within each of these arrays is set to the value 444.

### Delete

In [25]:
d = np.empty(c.shape)
np.copyto(d, c) # copy the values from c to d
d

array([[[   3.,   13.,   23.,   33.],
        [  43.,   53.,   63.,   73.],
        [  83.,   93.,  103.,  113.]],

       [[ 123.,  133.,  143.,  153.],
        [ 163.,  173.,  183.,  193.],
        [ 203.,  213.,  223.,  233.]]])

In [26]:
np.delete(d, 1, axis=0)

array([[[   3.,   13.,   23.,   33.],
        [  43.,   53.,   63.,   73.],
        [  83.,   93.,  103.,  113.]]])

The second of the large 2D array is deleted

In [27]:
np.delete(d, 1, axis=1)

array([[[   3.,   13.,   23.,   33.],
        [  83.,   93.,  103.,  113.]],

       [[ 123.,  133.,  143.,  153.],
        [ 203.,  213.,  223.,  233.]]])

The row that previously had index=1 from each 2D array within the original d array is deleted.

In [28]:
np.delete(d, 1, axis=2)

array([[[   3.,   23.,   33.],
        [  43.,   63.,   73.],
        [  83.,  103.,  113.]],

       [[ 123.,  143.,  153.],
        [ 163.,  183.,  193.],
        [ 203.,  223.,  233.]]])

The column that previously had index=1 from each 2D array within the original d array is deleted.