## Lynda.com
numpy boolean mask arrays

In [1]:
import numpy as np

In [4]:
my_vector = np.array([-17, -4, 0, 2, 21, 37, 105])
my_vector

array([-17,  -4,   0,   2,  21,  37, 105])

In [6]:
zero_mod_7_mask = 0 == (my_vector % 7) 
# select all elements in the array that the remainder after division by 7 is equal to 0
zero_mod_7_mask

array([False, False,  True, False,  True, False,  True], dtype=bool)

In [13]:
sub_array = my_vector[zero_mod_7_mask]
# this is the essential element of Boolean mask arrays
# I'm indexing "my_vector" with the results we created using "zero_mod_7_mask"
sub_array

array([  0,  21, 105])

In [11]:
# using the sub_array to index itself
sub_array[sub_array>0] # show only the elements that are greater than 0

array([ 21, 105])

In [14]:
sub_array

array([  0,  21, 105])

### NumPy Logical Operator
another method to achieve the same task

In [15]:
mod_test = 0 == (my_vector % 7) 
# select all elements in the array that the remainder after division by 7 is equal to 0

In [16]:
positive_test = my_vector > 0 # every element in "my_vector" which is greater than zero will be
# included in the variable "positive_test" via a boolean value

In [17]:
combined_mask = np.logical_and(mod_test, positive_test)
combined_mask # the result of "combine_mask" is same as "sub_array[sub_array>0]" 
# but in terms of boolean

array([False, False, False, False,  True, False,  True], dtype=bool)

In [18]:
# use combined_mask to index the original vector
my_vector[combined_mask]
# exactly the same result as "sub_array[sub_array>0]" 

array([ 21, 105])

Why do you need this logical functions for arrays? When you deal with very large arrays, numpy's logical functions will probably be more efficient.