## Lynda.com
numpy essential training: creating structured and record arrays

### Creating Structured Arrays

In [1]:
import numpy as np

In [3]:
person_data_def = [('name', 'S6'),('height','f8'),('weight','f8'),('age','i8')]
person_data_def
# the data def describes an array that has four fields
# the first is a string, which is named `name`
# the second is a floating point, named `height`
# the third is a floating point, named `weight`
# the four is an integer, named `age`

[('name', 'S6'), ('height', 'f8'), ('weight', 'f8'), ('age', 'i8')]

In [4]:
# use np.zeros function to create an array that contains four elements and
# has a data type that equals to our person_data_def
people_array = np.zeros((4), dtype=person_data_def)

In [6]:
# to view this people_array
people_array
# we see that it is now empty
# B indicates that it's a string
# note that the data type is included and it includes exactly our data definition

array([(b'', 0.0, 0.0, 0), (b'', 0.0, 0.0, 0), (b'', 0.0, 0.0, 0),
       (b'', 0.0, 0.0, 0)], 
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [7]:
# assign some values to the 4th element in people_array
people_array[3] = ('Delta', 73, 205, 34) 
# Delta as in Alpha, Beta, Charlie, Delta
# 73 as 73 inches for height
# 205 as 205 lbs for weight
# 34 for age
# name is a string so 'Delta' needs the parentheses
# height, weight = floating point, age = integer so no parentheses

In [8]:
# assign some values to the first element in people_array
people_array[0] = ('Alpha', 65, 12, 23)

In [10]:
# now display the array
people_array

array([(b'Alpha', 65.0, 12.0, 23), (b'', 0.0, 0.0, 0), (b'', 0.0, 0.0, 0),
       (b'Delta', 73.0, 205.0, 34)], 
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [11]:
# indexing the structured array
people_array[0:] # index zero through the last element

array([(b'Alpha', 65.0, 12.0, 23), (b'', 0.0, 0.0, 0), (b'', 0.0, 0.0, 0),
       (b'Delta', 73.0, 205.0, 34)], 
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [13]:
# use the names within our structured array for selection at our assignment
ages = people_array['age']
# instead of using numerical index, I can use a string index
ages
# the variable ages now has precisely the ages for the elements that we have already assigned

array([23,  0,  0, 34], dtype=int64)

In [14]:
# perform arithmetic calculations with arrays
make_youthful = ages / 2
make_youthful
# you should recognize that this operation did NOT change the original ages in the people_array

array([ 11.5,   0. ,   0. ,  17. ])

### Multidimensional Structured Arrays

In [15]:
people_big_array = np.zeros((4,3,2), dtype=person_data_def)
people_big_array

array([[[(b'', 0.0, 0.0, 0), (b'', 0.0, 0.0, 0)],
        [(b'', 0.0, 0.0, 0), (b'', 0.0, 0.0, 0)],
        [(b'', 0.0, 0.0, 0), (b'', 0.0, 0.0, 0)]],

       [[(b'', 0.0, 0.0, 0), (b'', 0.0, 0.0, 0)],
        [(b'', 0.0, 0.0, 0), (b'', 0.0, 0.0, 0)],
        [(b'', 0.0, 0.0, 0), (b'', 0.0, 0.0, 0)]],

       [[(b'', 0.0, 0.0, 0), (b'', 0.0, 0.0, 0)],
        [(b'', 0.0, 0.0, 0), (b'', 0.0, 0.0, 0)],
        [(b'', 0.0, 0.0, 0), (b'', 0.0, 0.0, 0)]],

       [[(b'', 0.0, 0.0, 0), (b'', 0.0, 0.0, 0)],
        [(b'', 0.0, 0.0, 0), (b'', 0.0, 0.0, 0)],
        [(b'', 0.0, 0.0, 0), (b'', 0.0, 0.0, 0)]]], 
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [16]:
# assign values using numerical index
people_big_array[3, 2, 1] = ('Echo', 68, 155, 46)

In [17]:
people_big_array

array([[[(b'', 0.0, 0.0, 0), (b'', 0.0, 0.0, 0)],
        [(b'', 0.0, 0.0, 0), (b'', 0.0, 0.0, 0)],
        [(b'', 0.0, 0.0, 0), (b'', 0.0, 0.0, 0)]],

       [[(b'', 0.0, 0.0, 0), (b'', 0.0, 0.0, 0)],
        [(b'', 0.0, 0.0, 0), (b'', 0.0, 0.0, 0)],
        [(b'', 0.0, 0.0, 0), (b'', 0.0, 0.0, 0)]],

       [[(b'', 0.0, 0.0, 0), (b'', 0.0, 0.0, 0)],
        [(b'', 0.0, 0.0, 0), (b'', 0.0, 0.0, 0)],
        [(b'', 0.0, 0.0, 0), (b'', 0.0, 0.0, 0)]],

       [[(b'', 0.0, 0.0, 0), (b'', 0.0, 0.0, 0)],
        [(b'', 0.0, 0.0, 0), (b'', 0.0, 0.0, 0)],
        [(b'', 0.0, 0.0, 0), (b'Echo', 68.0, 155.0, 46)]]], 
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [18]:
# display only 'height'
people_big_array['height']

array([[[  0.,   0.],
        [  0.,   0.],
        [  0.,   0.]],

       [[  0.,   0.],
        [  0.,   0.],
        [  0.,   0.]],

       [[  0.,   0.],
        [  0.,   0.],
        [  0.,   0.]],

       [[  0.,   0.],
        [  0.,   0.],
        [  0.,  68.]]])

In [19]:
# display both height and weight
people_big_array[['height', 'weight']]

array([[[(0.0, 0.0), (0.0, 0.0)],
        [(0.0, 0.0), (0.0, 0.0)],
        [(0.0, 0.0), (0.0, 0.0)]],

       [[(0.0, 0.0), (0.0, 0.0)],
        [(0.0, 0.0), (0.0, 0.0)],
        [(0.0, 0.0), (0.0, 0.0)]],

       [[(0.0, 0.0), (0.0, 0.0)],
        [(0.0, 0.0), (0.0, 0.0)],
        [(0.0, 0.0), (0.0, 0.0)]],

       [[(0.0, 0.0), (0.0, 0.0)],
        [(0.0, 0.0), (0.0, 0.0)],
        [(0.0, 0.0), (68.0, 155.0)]]], 
      dtype=[('height', '<f8'), ('weight', '<f8')])

### Creating Record Arrays

Record arrays are structured arrays wrapped using a sub-class of ndarray, called numpy.record array. This wrapping allows field access by attribute on an array object. Record arrays are also using a special data type, a numpy.record, which allows field access by attribute on the individual elements with an array.

In [21]:
person_record_array = np.rec.array([('Delta', 73, 205, 34), ('Alpha', 65, 112, 23)], dtype=person_data_def)
person_record_array

rec.array([(b'Delta', 73.0, 205.0, 34), (b'Alpha', 65.0, 112.0, 23)], 
          dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [22]:
# you can use an attribute in a record array to display values instead of an index
person_record_array[0].age # display the attribute 'age' for the first record 

34

Structured and record arrays are designed for heterogeneous data